In [1]:
import numpy as np

# Numpy Phase 1

# Create a array
    - np.array([list]) # give only one list argument

In [2]:
array = np.array([1, 2, 3])
print(array)

[1 2 3]


# use arange to create an array
    - np.arange(start,stop,step)


In [3]:
array = np.arange(1, 11, 1)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


# zero, one, full, random array
    - np.zeros((row,col))
    - np.ones((row,col))
    - np.full((row,col),value)
    - np.random.random((row,col))

In [4]:
zero_array = np.zeros((2, 3))
print("zero array :\n", zero_array)

one_array = np.ones((2, 4))
print("one array :\n", one_array)

full_array = np.full((2, 3), 9)
print("full array :\n", full_array)

random_array = np.random.random((2, 3))
print("random array :\n", random_array)


zero array :
 [[0. 0. 0.]
 [0. 0. 0.]]
one array :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array :
 [[9 9 9]
 [9 9 9]]
random array :
 [[0.41762525 0.87850223 0.71845434]
 [0.8081193  0.91900208 0.64828308]]


# Vectors , Matrices and Tensors
    - 1D array is called vector
    - 2D array is called matrix
    - 3D array or higher dimension array is called tensor


In [5]:
vector = np.array([1, 2, 3])
print("vector :\n", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("matrix :\n", matrix)

tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("tensor :\n", tensor)

vector :
 [1 2 3]
matrix :
 [[1 2 3]
 [4 5 6]]
tensor :
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Array properties
    - ndim : number of dimensions
    - shape : shape of array
    - size : total number of elements
    - dtype : data type of elements

In [6]:
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

print("shape = ", array.shape)
print("dimensions = ", array.ndim)
print("size = ", array.size)
print("datatype = ",array.dtype)

shape =  (2, 3)
dimensions =  2
size =  6
datatype =  int64


# Array reshaping
    - reshape(row,col) # change shape of array
    - flatten() # convert multi-dim array to 1D array
    - ravel() # convert multi-dim array to 1D array (view)
    - transpose() # transpose of array

In [7]:
array=np.arange(1,9,1)
print("original array = ",array)

reshape_array=array.reshape((2,4))
print("reshaped array = \n",reshape_array)

flatten_array=reshape_array.flatten()
print("flatten array = ",flatten_array)

ravel_array=reshape_array.ravel()
print("ravel array = ",ravel_array)

transpose=reshape_array.transpose()
print("transpose = \n",transpose)

original array =  [1 2 3 4 5 6 7 8]
reshaped array = 
 [[1 2 3 4]
 [5 6 7 8]]
flatten array =  [1 2 3 4 5 6 7 8]
ravel array =  [1 2 3 4 5 6 7 8]
transpose = 
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


# diffrence between flatten and ravel
    - flatten() returns a copy of the array
    - ravel() returns a view of the array (if possible)
    example:

In [8]:
array=np.arange(1,9,1)
reshape_array=array.reshape((2,4))
print("original array = \n",reshape_array)

ravel_array=reshape_array.ravel()
print("ravel array = ",ravel_array)

ravel_array[0]=10
print("after changing ravel array = ",ravel_array)
print("original array after changing ravel array = \n",reshape_array)

flatten_array=reshape_array.flatten()
print("flatten array = ",flatten_array)

flatten_array[0]=20
print("after changing flatten array = ",flatten_array)
print("original array after changing flatten array = \n",reshape_array)

original array = 
 [[1 2 3 4]
 [5 6 7 8]]
ravel array =  [1 2 3 4 5 6 7 8]
after changing ravel array =  [10  2  3  4  5  6  7  8]
original array after changing ravel array = 
 [[10  2  3  4]
 [ 5  6  7  8]]
flatten array =  [10  2  3  4  5  6  7  8]
after changing flatten array =  [20  2  3  4  5  6  7  8]
original array after changing flatten array = 
 [[10  2  3  4]
 [ 5  6  7  8]]
