In [3]:
import numpy as np

# Numpy Array Operations
    1. Array Slicing (1D)

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("basic slicing = ", arr[2:6])  # 2 to 5 index
print("basic slicing = ", arr[4:])  # 4 to end
print("basic slicing = ", arr[:6])  # 0 to 5 index
print("basic slicing = ", arr[-3])  # access from last third element
print("basic slicing = ", arr[-5:-2])  # access from last fifth to last second element
print("with step = ", arr[1:8:2])  # 1 to 7 index with step 2
print("with step = ", arr[::2])  # all elements with step 2
print("with step = ", arr[1::2])  # 1 to end with step 2

basic slicing =  [3 4 5 6]
basic slicing =  [ 5  6  7  8  9 10]
basic slicing =  [1 2 3 4 5 6]
basic slicing =  8
basic slicing =  [6 7 8]
with step =  [2 4 6 8]
with step =  [1 3 5 7 9]
with step =  [ 2  4  6  8 10]


    2. Array Slicing (2D)

In [47]:
array_2d = np.array([[1, 2, 3, 4, 5, 6],
                     [4, 5, 6, 7, 8, 9],
                     [7, 8, 9, 0, 1, 2]])
print("element at (1,1) = ", array_2d[1, 1])  # 5
print("get rows at 1 index = ", array_2d[1])  # [4,5,6]
print("get column at 1 index = ", array_2d[:, 1])  # [2,5,8]

# array_2d[start_row:end_row:step_row, start_col:end_col:step_col]
'''
explanation of below slicing
array_2d[1:3,1:7:2]
1:3 means rows from index 1 to 2 (3 is excluded)
1:7:2 means columns from index 1 to 6 with step 2 (7 is excluded)
'''
print(array_2d[1:3, 1:7:2])

element at (1,1) =  5
get rows at 1 index =  [4 5 6 7 8 9]
get column at 1 index =  [2 5 8]
[[5 7 9]
 [8 0 2]]


    3. Sorting an Array

In [57]:
# sorting 1D array

# np.sort(array,axis=0/1) # axis=0 for column wise sorting, axis=1 for row wise sorting
# default axis=1
unsorted_array_1d = np.array([1, 6, 3, 8, 3, 1, 6, 0, 5])
print("unsorted array 1D = ", unsorted_array_1d)
print("sorted array 1D = ", np.sort(unsorted_array_1d))

# sorting 2D array
unsorted_array_2d = np.array([[6, 5, 0],
                              [2, 3, 1],
                              [8, 6, 2]])
print("unsorted array 2D = \n", unsorted_array_2d)
print("sorted array 2D row wise = \n", np.sort(unsorted_array_2d, axis=1))
print("sorted array 2D column wise = \n", np.sort(unsorted_array_2d, axis=0))

unsorted array 1D =  [1 6 3 8 3 1 6 0 5]
sorted array 1D =  [0 1 1 3 3 5 6 6 8]
unsorted array 2D = 
 [[6 5 0]
 [2 3 1]
 [8 6 2]]
sorted array 2D row wise = 
 [[0 5 6]
 [1 2 3]
 [2 6 8]]
sorted array 2D column wise = 
 [[2 3 0]
 [6 5 1]
 [8 6 2]]


    4. Filtering an Array

In [5]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
'''
# filtering :
    - apply condition on array to filter elements
    - returns a new array with elements that satisfy the condition
    syntax: array[condition]
'''
even = numbers[numbers % 2 == 0]
print("even number = ", even)
'''
# filtering with mask
    - create a boolean mask with condition
    - apply the mask to the array
    syntax:
        mask = array[condition]
        array[mask]
'''
masked = numbers > 5
print("filter with mask = ", numbers[masked])

even number =  [ 2  4  6  8 10]
filter with mask =  [ 6  7  8  9 10]
[1 3 5]


    5. Fancy Indexing vs. np.Where()

In [10]:
'''
# fancy indexing :
    - access multiple array elements at once using list of indices
    - returns a new array with elements at the specified indices
    syntax: array[[index1,index2,index3,...]]
'''
indicis = [0, 2, 4]
print(numbers[indicis])

'''
# np.where() :
    - returns the indices of elements that satisfy the condition
    - can be used for conditional selection and replacement
    syntax: np.where(condition)
'''
where_result = np.where(numbers > 5)
print("using where = ", numbers[where_result])

'''
# conditional selection and replacement
    - np.where(condition, x, y)
    - if condition is true, select x else select y
    syntax: np.where(condition, x, y)
'''
conditional_array=np.where(numbers>5,numbers*2,numbers)
print("conditional array = ",conditional_array)

[1 3 5]
using where =  [ 6  7  8  9 10]
conditional array =  [ 1  2  3  4  5 12 14 16 18 20]


    6. Adding and Removing Elements

In [22]:
a1=np.array([3,2,8,9])
a2=np.array([7,4,1,6])

print(a1+a2) # element wise addition
print(np.concatenate((a1,a2))) # concatenate two arrays

array_2d=np.array([[1,2,3],[4,5,6]])
new_row=np.array([[7,8,9]])
new_col=np.array([[10],[11]])
print("add row = \n",np.vstack((array_2d,new_row))) # add row
print("add column = \n",np.hstack((array_2d,new_col))) # add column

print("before deletion = ",a1)
deleted=np.delete(a1,2) # delete element at index 2
print("after deletion = ",deleted)

[10  6  9 15]
[3 2 8 9 7 4 1 6]
add row = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
add column = 
 [[ 1  2  3 10]
 [ 4  5  6 11]]
before deletion =  [3 2 8 9]
after deletion =  [3 2 9]
