In [27]:
import numpy as np

## 📌 Vectorization
    - Meaning: Perform operations on entire arrays at once (no explicit loops).
    - Why: Much faster (uses optimized C code + SIMD instructions), cleaner code.
    - How: arr * 2, arr + 10, arr1 + arr2 → apply to all elements automatically.
    - Internals:
        - Checks array dtype
        - Allocates new array
        - Runs compiled C loop (very fast)
    - Example:
        arr = np.array([1, 2, 3, 4, 5])
        result = arr * 2  # Vectorized
    - Real-life use:
        - Sales data → price increase, currency conversion, profit calculation — all in one line.
    - Benefits:
        - Faster than Python loops
        - Cleaner and shorter code
        - Memory efficient

## 📌 Linear Algebra with NumPy
    (1) Matrix Multiplication
        - Use np.dot() or @ operator.
    (2) Determinant
        - Use np.linalg.det().
    (3) Inverse
        - Use np.linalg.inv().
    (4) Eigenvalues and Eigenvectors
        - Use np.linalg.eig().
    (5) Solving Linear Systems
        - Use np.linalg.solve().
    (6) Norms
        - Use np.linalg.norm().

In [28]:
# Example: Matrix Multiplication
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
C = np.dot(A, B)  # or C = A @ B
print("Matrix Multiplication:\n", C)

# Example: Determinant
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

# Example: Inverse
inv_A = np.linalg.inv(A)
print("Inverse of A:\n", inv_A)

# Example: Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)

# Example: Solving Linear Systems
A = np.array([[3, 1],
              [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
print("Solution of Ax = b:", x)

# Example: Norms
norm_A = np.linalg.norm(A)
print("Norm of A:", norm_A)

Matrix Multiplication:
 [[19 22]
 [43 50]]
Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues of A: [-0.37228132  5.37228132]
Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Solution of Ax = b: [2. 3.]
Norm of A: 3.872983346207417


## 📌 Saving and Loading NumPy Arrays
    - Save with np.save() for single arrays (.npy) or np.savez() for multiple arrays (.npz).
    - Load with np.load().
    - Benefits:
        - Efficient storage
        - Easy to share and reuse data

In [29]:
array=np.array([11,2,3,45,6])
array3=np.array([11,2,3,45,6])
np.save('array.npy',array)
print("array save successfully")

loaded_array=np.load('array.npy')
print("loaded array = ",loaded_array)

array2=np.array([1,2,57,2,15])
np.savez('multipal_array.npz',x=array,y=array2,a=array3)
print("multipal array save successfully")

loaded_data=np.load('multipal_array.npz')
print("array 1 = ",loaded_data['x'])
print("array 2 = ",loaded_data['y'])
print("array 3 = ",loaded_data['a'])

array save successfully
loaded array =  [11  2  3 45  6]
multipal array save successfully
array 1 =  [11  2  3 45  6]
array 2 =  [ 1  2 57  2 15]
array 3 =  [11  2  3 45  6]


### Deep Copy (np.copy())
    - A deep copy creates a brand new array with a new copy of the data.
    - Any changes you make to the copy will not affect the original array.
    - Think of it as photocopying a document;
    - writing on the photocopy doesn't change the original paper.

    - Syntax: new_array = np.copy(original_array)

### Shallow Copy (arr.view())
- A shallow copy, or a view, creates a new array object but it shares the same data as the original array.
- Any changes you make to the data in the view will affect the original array.
- Think of it as having two different windows looking at the same garden;
- if you change something in the garden through one window,
- the view from the other window also changes.

        - Syntax: new_array = original_array.view()

### Deep vs Shallow Copy Summary
| Feature          | Deep Copy (np.copy())         | Shallow Copy (arr.view())         |
|------------------|-------------------------------|-------------------------------------|
| Data Independence | Independent copy of data      | Shares data with original array     |
| Memory Usage     | More memory (new data)        | Less memory (shared data)           |
| Modification Effect | Changes do not affect original | Changes affect original             |


In [30]:
original_array = np.array([1, 2, 3, 4, 5])
print("Original Array:", original_array)
deep_copied_array = np.copy(original_array)
print("Deep Copied Array:", deep_copied_array)
shallow_copied_array = original_array.view()
print("Shallow Copied Array:", shallow_copied_array)

# Modify the deep copy
deep_copied_array[0] = 99
print("\nAfter modifying deep copy:")
print("Original Array:", original_array)  # Unchanged
print("Deep Copied Array:", deep_copied_array)  # Changed
print("Shallow Copied Array:", shallow_copied_array)  # Unchanged

# Modify the shallow copy
shallow_copied_array[1] = 88
print("\nAfter modifying shallow copy:")
print("Original Array:", original_array)  # Changed
print("Deep Copied Array:", deep_copied_array)  # Unchanged
print("Shallow Copied Array:", shallow_copied_array)  # Changed

Original Array: [1 2 3 4 5]
Deep Copied Array: [1 2 3 4 5]
Shallow Copied Array: [1 2 3 4 5]

After modifying deep copy:
Original Array: [1 2 3 4 5]
Deep Copied Array: [99  2  3  4  5]
Shallow Copied Array: [1 2 3 4 5]

After modifying shallow copy:
Original Array: [ 1 88  3  4  5]
Deep Copied Array: [99  2  3  4  5]
Shallow Copied Array: [ 1 88  3  4  5]


## 📌 Iterating Over NumPy Arrays
- Use np.nditer() for efficient iteration over arrays of any shape.
- Supports multidimensional arrays and various iteration orders (C-style, Fortran-style).
- Can modify array elements in place using op_flags=['readwrite'].
    -     Syntax: for x in np.nditer(array, order='C' or 'F', op_flags=['readwrite'])

In [31]:
np.random.seed(0)
original_array=np.random.randint(1,10,(2,3,4))
print("original array = \n",original_array)

for i in np.nditer(original_array,order='F',op_flags=['readwrite']):
    if i>5:
        print(i,end=" ")
        i[...]=i-5

print("\nmodified array = \n",original_array)

original array = 
 [[[6 1 4 4]
  [8 4 6 3]
  [5 8 7 9]]

 [[9 2 7 8]
  [8 9 2 6]
  [9 5 4 1]]]
6 9 8 8 9 9 8 7 6 7 8 6 9 
modified array = 
 [[[1 1 4 4]
  [3 4 1 3]
  [5 3 2 4]]

 [[4 2 2 3]
  [3 4 2 1]
  [4 5 4 1]]]


## 📌 Memory Layout of arrays using flags attribute
    - NumPy arrays have a flags attribute that provides information about the memory layout and properties of the array.
    - Important flags:
        - C_CONTIGUOUS (C order): Data is stored in row-major order (last index changes fastest).
        - F_CONTIGUOUS (Fortran order): Data is stored in column-major order (first index changes fastest).
        - OWNDATA: Indicates if the array owns its data or is a view of another array.
        - WRITEABLE: Indicates if the array's data can be modified.
        - ALIGNED: Indicates if the data is aligned in memory for efficient access.

In [32]:
# Complex example to show flags
array=np.array([[1,2,3],[4,5,6]],order='F')
print("array = \n",array)
print("array flags = \n",array.flags)
print("Is array C_CONTIGUOUS? ",array.flags['C_CONTIGUOUS'])
print("Is array F_CONTIGUOUS? ",array.flags['F_CONTIGUOUS'])
print("Does array own its data (OWN DATA)? ",array.flags['OWNDATA'])
print("Is array WRITEABLE? ",array.flags['WRITEABLE'])
print("Is array ALIGNED? ",array.flags['ALIGNED'])

array = 
 [[1 2 3]
 [4 5 6]]
array flags = 
   C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

Is array C_CONTIGUOUS?  False
Is array F_CONTIGUOUS?  True
Does array own its data (OWN DATA)?  True
Is array WRITEABLE?  True
Is array ALIGNED?  True
